/** Used when the reset-password success page loads before its settings exist. */
export const RESET_PASSWORD_SUCCESS_DEFAULTS = {
  reset_password_success_title: "Password Reset Successful",
  reset_password_success_description: "Your password has been reset successfully. You can now sign in with your new password.",
  reset_password_success_redirect_url: "/login",
  reset_password_success_redirect_label: "Sign In Now",
  reset_password_success_auto_redirect: "true",
};

/**
 * Label for the link the auth pages carry back to the quick-entry home page.
 *
 * Also the value the seed stores, but the pages fall back to it: the setting only exists after the
 * release that adds it has been seeded, and an unlabelled link is worse than a stale one.
 */
export const QUICK_TRANSACTION_LINK_DEFAULT = "Record a transaction without signing in";

export const CONTENT_SETTINGS = [
  // general information settings
  {
    key: "footer_copyright",
    value: "© 2026 Finarthax. All rights reserved.",
    type: "string",
    category: "general_information",
    label: "Footer Copyright",
    description: "Copyright text displayed in the website footer",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "social_login_separator",
    value: "Or continue with",
    type: "string",
    category: "general_information",
    label: "Social Login Separator Text",
    description: "Text displayed between the login form and social authentication buttons",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "signin_text",
    value: "Sign in",
    type: "string",
    category: "general_information",
    label: "Register Link Text",
    description: "Text for the sign up link",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "signup_text",
    value: "Sign up",
    type: "string",
    category: "general_information",
    label: "Login Link Text",
    description: "Text for the sign in link",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "google_signup_button",
    value: "Sign up with Google",
    type: "string",
    category: "general_information",
    label: "Google Sign Up Button Text",
    description: "Text displayed on the Google sign up button",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "quick_transaction_link_text",
    value: QUICK_TRANSACTION_LINK_DEFAULT,
    type: "string",
    category: "general_information",
    label: "Quick Transaction Link Text",
    description: "Text for the link from the login and register pages back to the quick-entry home page",
    sortOrder: 0,
    isPublic: true,
  },

  // Home page information settings
  {
    key: "home_title",
    value: "Finarthax",
    type: "string",
    category: "home_page_information",
    label: "Home Title",
    description: "Main title on homepage",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "home_description",
    value: "Record your transactions instantly, no login required",
    type: "string",
    category: "home_page_information",
    label: "Home Description",
    description: "Homepage description",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "how_it_works_title",
    value: "How it works:",
    type: "string",
    category: "home_page_information",
    label: "How It Works Title",
    description: "How it works section title",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "ready_for_more_title",
    value: "Ready for More?",
    type: "string",
    category: "home_page_information",
    label: "Ready For More Title",
    description: "Marketing section title",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "ready_for_more_description",
    value: "Create a free account to sync your data, set budgets, and access powerful analytics",
    type: "string",
    category: "home_page_information",
    label: "Ready For More Description",
    description: "Marketing section description",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "how_it_works_content",
    value: JSON.stringify([
      "Record transactions without creating an account",
      "Transactions saved locally on your device",
      "Perfect for quick expense tracking on the go",
      "Sign up later to sync and access advanced features",
    ]),
    type: "json",
    category: "home_page_information",
    label: "How It Works Content",
    description: "How it works section bullet points",
    sortOrder: 0,
    isPublic: true,
  },

  // Login page information settings
  {
    key: "login_title",
    value: "Welcome back",
    type: "string",
    category: "login_page_information",
    label: "Login Title",
    description: "Login title on login page",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "login_description",
    value: "Sign in to continue to your account",
    type: "string",
    category: "login_page_information",
    label: "Login Description",
    description: "Login page description",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "login_forgot_password_text",
    value: "Forgot password?",
    type: "string",
    category: "login_page_information",
    label: "Forgot Password Text",
    description: "Text displayed for the forgot password link",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "login_prompt_text",
    value: "Already have an account?",
    type: "string",
    category: "login_page_information",
    label: "Login Prompt Text",
    description: "Text displayed before the sign in link",
    sortOrder: 0,
    isPublic: true,
  },

  // Register page information settings
  {
    key: "register_title",
    value: "Create account",
    type: "string",
    category: "register_page_information",
    label: "Register Title",
    description: "Register title on register page",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "register_description",
    value: "Get started with your free account",
    type: "string",
    category: "register_page_information",
    label: "Register Description",
    description: "Register page description",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "register_password_requirements",
    value: "Password must contain:",
    type: "string",
    category: "register_page_information",
    label: "Password Requirements Title",
    description: "Title displayed above the password requirements list",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "register_password_requirements_list",
    value: JSON.stringify(["At least 8 characters", "One uppercase letter", "One lowercase letter", "One number"]),
    type: "json",
    category: "register_page_information",
    label: "Password Requirements",
    description: "List of password requirements displayed on authentication forms",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "register_button_create_account_text",
    value: "Create Account",
    type: "string",
    category: "register_page_information",
    label: "Create Account Button Text",
    description: "Text displayed on the create account button",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "register_confirmation_text",
    value: "I confirm that the information provided is accurate.",
    type: "string",
    category: "register_page_information",
    label: "Registration Confirmation Text",
    description: "Confirmation statement displayed during user registration",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "register_prompt_text",
    value: "Don't have an account?",
    type: "string",
    category: "register_page_information",
    label: "Register Prompt Text",
    description: "Text displayed before the sign up link",
    sortOrder: 0,
    isPublic: true,
  },

  // Forgot password page information settings
  {
    key: "forgot_password_title",
    value: "Forgot your password?",
    type: "string",
    category: "forgot_password_page_information",
    label: "Forgot Password Title",
    description: "Main heading displayed on the forgot password page",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "forgot_password_description",
    value: "No worries! Enter your email address and we'll send you a link to reset your password.",
    type: "string",
    category: "forgot_password_page_information",
    label: "Forgot Password Description",
    description: "Description displayed below the forgot password title",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "forgot_password_notice",
    value: "We'll send you an email with instructions to reset your password. The link will be valid for 1 hour.",
    type: "string",
    category: "forgot_password_page_information",
    label: "Forgot Password Notice",
    description: "Information displayed before the reset password button",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "forgot_password_button_text",
    value: "Send Reset Link",
    type: "string",
    category: "forgot_password_page_information",
    label: "Send Reset Link Button Text",
    description: "Text displayed on the send reset link button",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "forgot_password_prompt_text",
    value: "Back to Sign In",
    type: "string",
    category: "forgot_password_page_information",
    label: "Back to Sign In Text",
    description: "Text displayed for the back to sign in link",
    sortOrder: 0,
    isPublic: true,
  },

  // Reset password page information settings
  {
    key: "reset_password_title",
    value: "Reset your password",
    type: "string",
    category: "reset_password_page_information",
    label: "Reset Password Title",
    description: "Main heading displayed on the reset password page",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "reset_password_description",
    value: "Enter your new password below",
    type: "string",
    category: "reset_password_page_information",
    label: "Reset Password Description",
    description: "Description displayed below the reset password title",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "reset_password_requirements",
    value: "Password requirements:",
    type: "string",
    category: "reset_password_page_information",
    label: "Password Requirements Title",
    description: "Title displayed before the password requirements list",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "reset_password_requirements_list",
    value: JSON.stringify(["At least 8 characters long", "Must match confirmation"]),
    type: "json",
    category: "reset_password_page_information",
    label: "Password Requirements",
    description: "List of password requirements displayed on authentication pages",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "reset_password_button_text",
    value: "Reset Password",
    type: "string",
    category: "reset_password_page_information",
    label: "Reset Password Button Text",
    description: "Text displayed on the reset password button",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "reset_password_prompt_text",
    value: "Remember your password?",
    type: "string",
    category: "reset_password_page_information",
    label: "Remember Password Text",
    description: "Text displayed before the sign in link",
    sortOrder: 0,
    isPublic: true,
  },

  // Reset password success page information settings
  {
    key: "reset_password_success_title",
    value: "Password Reset Successful",
    type: "string",
    category: "reset_password_success_page_information",
    label: "Success Page Title",
    description: "Main heading displayed on the password reset success page",
    sortOrder: 0,
    isPublic: false,
  },
  {
    key: "reset_password_success_description",
    value: "Your password has been reset successfully. You can now sign in with your new password.",
    type: "string",
    category: "reset_password_success_page_information",
    label: "Success Page Description",
    description: "Description displayed on the password reset success page",
    sortOrder: 0,
    isPublic: false,
  },
  {
    key: "reset_password_success_redirect_url",
    value: "/login",
    type: "string",
    category: "reset_password_success_page_information",
    label: "Redirect URL",
    description: "Destination URL used when redirecting from the success page",
    sortOrder: 0,
    isPublic: false,
  },
  {
    key: "reset_password_success_redirect_label",
    value: "Sign In Now",
    type: "string",
    category: "reset_password_success_page_information",
    label: "Redirect Button Label",
    description: "Text displayed on the button that redirects the user to the configured URL",
    sortOrder: 0,
    isPublic: false,
  },
  {
    key: "reset_password_success_auto_redirect",
    value: "true",
    type: "boolean",
    category: "reset_password_success_page_information",
    label: "Enable Auto Redirect",
    description: "Whether users are automatically redirected after the countdown finishes",
    sortOrder: 0,
    isPublic: false,
  },
  {
    key: "reset_password_success_redirect_countdown_text",
    value: "Redirecting in {seconds} seconds...",
    type: "string",
    category: "reset_password_success_page_information",
    label: "Redirect Countdown Message",
    description: "Message displayed while counting down before automatic redirection",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "reset_password_success_redirect_countdown_seconds",
    value: "5",
    type: "string",
    category: "reset_password_success_page_information",
    label: "Redirect Countdown Duration",
    description: "Number of seconds to wait before automatically redirecting the user",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "reset_password_success_button_text",
    value: "Go to Home",
    type: "string",
    category: "reset_password_success_page_information",
    label: "Secondary Button Label",
    description: "Text displayed on the secondary action button",
    sortOrder: 0,
    isPublic: true,
  },
];
