export const EXCHANGE_RATE_URL = process.env.EXCHANGE_RATE_URL || "https://api.exchangerate-api.com/v4/latest";
export const BASE_CURRENCY = process.env.BASE_CURRENCY || "IDR";
export const BASE_CURRENCY_SYMBOL = process.env.BASE_CURRENCY_SYMBOL || "Rp";

export const DEFAULT_SETTINGS = [
  {
    key: "emailNotifications",
    value: "true",
    type: "boolean",
    category: "notifications",
    description: "Receive email notifications",
    icon: "📩",
  },
  {
    key: "budgetAlerts",
    value: "true",
    type: "boolean",
    category: "notifications",
    description: "Get alerts when approaching budget limits",
    icon: "💰",
  },
  {
    key: "weeklyReports",
    value: "true",
    type: "boolean",
    category: "notifications",
    description: "Receive weekly financial reports",
    icon: "📊",
  },
  {
    key: "transactionAlerts",
    value: "true",
    type: "boolean",
    category: "notifications",
    description: "Get notified of new transactions",
    icon: "🔔",
  },
  {
    key: "marketingEmails",
    value: "true",
    type: "boolean",
    category: "notifications",
    description: "Receive marketing and promotional emails",
    icon: "📢",
  },
  {
    key: "language",
    value: "en",
    type: "string",
    category: "general",
    description: "Interface language",
    icon: "🌐",
  },
  {
    key: "currency",
    value: "IDR",
    type: "string",
    category: "general",
    description: "Default currency for transactions",
    icon: "💰",
  },
  {
    key: "theme",
    value: "light",
    type: "string",
    category: "appearance",
    description: "Interface theme",
    icon: "🎨",
  },
];

export const CURRENCY_OPTIONS = [
  { value: "USD", label: "🇺🇸 USD - US Dollar", symbol: "$" },
  { value: "EUR", label: "🇪🇺 EUR - Euro", symbol: "€" },
  { value: "JPY", label: "🇯🇵 JPY - Japanese Yen", symbol: "¥" },
  { value: "GBP", label: "🇬🇧 GBP - British Pound", symbol: "£" },
  { value: "AUD", label: "🇦🇺 AUD - Australian Dollar", symbol: "A$" },
  { value: "CAD", label: "🇨🇦 CAD - Canadian Dollar", symbol: "C$" },
  { value: "CHF", label: "🇨🇭 CHF - Swiss Franc", symbol: "CHF" },
  { value: "CNY", label: "🇨🇳 CNY - Chinese Yuan", symbol: "¥" },
  { value: "IDR", label: "🇮🇩 IDR - Indonesian Rupiah", symbol: "Rp" },
  { value: "HKD", label: "🇭🇰 HKD - Hong Kong Dollar", symbol: "HK$" },
];

export const LANGUAGE_OPTIONS = [
  { value: "en", label: "🇺🇸 English" },
  { value: "id", label: "🇮🇩 Indonesia" },
  { value: "zh", label: "🇨🇳 Chinese" },
];

export const THEME_OPTIONS = [
  { value: "light", label: "☀️ Light" },
  { value: "dark", label: "🌙 Dark" },
  { value: "system", label: "💻 System" },
];

export const CURRENCY_LOCALE_MAP = {
  USD: "en-US",
  EUR: "de-DE",
  GBP: "en-GB",
  JPY: "ja-JP",
  CNY: "zh-CN",
  IDR: "id-ID",
  SGD: "en-SG",
  MYR: "ms-MY",
  THB: "th-TH",
  VND: "vi-VN",
  PHP: "en-PH",
  KRW: "ko-KR",
  INR: "en-IN",
  PKR: "ur-PK",
  BDT: "bn-BD",
  AED: "ar-AE",
  SAR: "ar-SA",
  QAR: "ar-QA",
  KWD: "ar-KW",
  OMR: "ar-OM",
  ILS: "he-IL",
  TRY: "tr-TR",
  CHF: "de-CH",
  NOK: "nb-NO",
  SEK: "sv-SE",
  DKK: "da-DK",
  PLN: "pl-PL",
  CZK: "cs-CZ",
  HUF: "hu-HU",
  RON: "ro-RO",
  BGN: "bg-BG",
  HRK: "hr-HR",
  CAD: "en-CA",
  AUD: "en-AU",
  NZD: "en-NZ",
  MXN: "es-MX",
  BRL: "pt-BR",
  ARS: "es-AR",
  CLP: "es-CL",
  COP: "es-CO",
  PEN: "es-PE",
  ZAR: "en-ZA",
  NGN: "en-NG",
  EGP: "ar-EG",
  KES: "en-KE",
  GHS: "en-GH",
  MAD: "ar-MA",
  TZS: "sw-TZ",
};

export const ZERO_DECIMAL_CURRENCIES: Record<string, string> = {
  BIF: "rn-BI",
  CLP: "es-CL",
  DJF: "fr-DJ",
  GNF: "fr-GN",
  IDR: "id-ID",
  JPY: "ja-JP",
  KMF: "ar-KM",
  KRW: "ko-KR",
  MGA: "mg-MG",
  PYG: "es-PY",
  RWF: "rw-RW",
  UGX: "en-UG",
  UYI: "es-UY",
  VND: "vi-VN",
  VUV: "bi-VU",
  XAF: "fr-CM",
  XOF: "fr-SN",
  XPF: "fr-PF",
};
