export const EXCHANGE_RATE_URL = process.env.EXCHANGE_RATE_URL || "https://api.exchangerate-api.com/v4/latest";
export const BASE_CURRENCY = process.env.BASE_CURRENCY || "IDR";
export const BASE_CURRENCY_SYMBOL = process.env.BASE_CURRENCY_SYMBOL || "Rp";

export const DEFAULT_SETTINGS = [
  {
    key: "emailNotifications",
    value: "true",
    type: "boolean",
    category: "notifications",
    description: "Receive email notifications",
    icon: "📩",
  },
  {
    key: "budgetAlerts",
    value: "true",
    type: "boolean",
    category: "notifications",
    description: "Get alerts when approaching budget limits",
    icon: "💰",
  },
  {
    key: "weeklyReports",
    value: "true",
    type: "boolean",
    category: "notifications",
    description: "Receive weekly financial reports",
    icon: "📊",
  },
  {
    key: "transactionAlerts",
    value: "true",
    type: "boolean",
    category: "notifications",
    description: "Get notified of new transactions",
    icon: "🔔",
  },
  {
    key: "marketingEmails",
    value: "true",
    type: "boolean",
    category: "notifications",
    description: "Receive marketing and promotional emails",
    icon: "📢",
  },
  {
    key: "language",
    value: "en",
    type: "string",
    category: "appearance",
    description: "Interface language",
    icon: "🌐",
  },
  {
    key: "currency",
    value: "IDR",
    type: "string",
    category: "appearance",
    description: "Default currency for transactions",
    icon: "💰",
  },
  {
    key: "theme",
    value: "light",
    type: "string",
    category: "appearance",
    description: "Interface theme",
    icon: "🎨",
  },
];

export const CURRENCY_OPTIONS = [
  { value: "USD", label: "🇺🇸 USD - US Dollar", symbol: "$" },
  { value: "EUR", label: "🇪🇺 EUR - Euro", symbol: "€" },
  { value: "JPY", label: "🇯🇵 JPY - Japanese Yen", symbol: "¥" },
  { value: "GBP", label: "🇬🇧 GBP - British Pound", symbol: "£" },
  { value: "AUD", label: "🇦🇺 AUD - Australian Dollar", symbol: "A$" },
  { value: "CAD", label: "🇨🇦 CAD - Canadian Dollar", symbol: "C$" },
  { value: "CHF", label: "🇨🇭 CHF - Swiss Franc", symbol: "CHF" },
  { value: "CNY", label: "🇨🇳 CNY - Chinese Yuan", symbol: "¥" },
  { value: "IDR", label: "🇮🇩 IDR - Indonesian Rupiah", symbol: "Rp" },
  { value: "HKD", label: "🇭🇰 HKD - Hong Kong Dollar", symbol: "HK$" },
];

export const LANGUAGE_OPTIONS = [
  { value: "en", label: "🇺🇸 English" },
  { value: "id", label: "🇮🇩 Indonesia" },
  { value: "zh", label: "🇨🇳 Chinese" },
];

export const THEME_OPTIONS = [
  { value: "light", label: "☀️ Light" },
  { value: "dark", label: "🌙 Dark" },
  { value: "system", label: "💻 System" },
];

export const CURRENCY_LOCALE_MAP = {
  USD: "en-US",
  EUR: "de-DE",
  GBP: "en-GB",
  JPY: "ja-JP",
  CNY: "zh-CN",
  IDR: "id-ID",
  SGD: "en-SG",
  MYR: "ms-MY",
  THB: "th-TH",
  VND: "vi-VN",
  PHP: "en-PH",
  KRW: "ko-KR",
  INR: "en-IN",
  PKR: "ur-PK",
  BDT: "bn-BD",
  AED: "ar-AE",
  SAR: "ar-SA",
  QAR: "ar-QA",
  KWD: "ar-KW",
  OMR: "ar-OM",
  ILS: "he-IL",
  TRY: "tr-TR",
  CHF: "de-CH",
  NOK: "nb-NO",
  SEK: "sv-SE",
  DKK: "da-DK",
  PLN: "pl-PL",
  CZK: "cs-CZ",
  HUF: "hu-HU",
  RON: "ro-RO",
  BGN: "bg-BG",
  HRK: "hr-HR",
  CAD: "en-CA",
  AUD: "en-AU",
  NZD: "en-NZ",
  MXN: "es-MX",
  BRL: "pt-BR",
  ARS: "es-AR",
  CLP: "es-CL",
  COP: "es-CO",
  PEN: "es-PE",
  ZAR: "en-ZA",
  NGN: "en-NG",
  EGP: "ar-EG",
  KES: "en-KE",
  GHS: "en-GH",
  MAD: "ar-MA",
  TZS: "sw-TZ",
};

export const ZERO_DECIMAL_CURRENCIES: Record<string, string> = {
  BIF: "rn-BI",
  CLP: "es-CL",
  DJF: "fr-DJ",
  GNF: "fr-GN",
  IDR: "id-ID",
  JPY: "ja-JP",
  KMF: "ar-KM",
  KRW: "ko-KR",
  MGA: "mg-MG",
  PYG: "es-PY",
  RWF: "rw-RW",
  UGX: "en-UG",
  UYI: "es-UY",
  VND: "vi-VN",
  VUV: "bi-VU",
  XAF: "fr-CM",
  XOF: "fr-SN",
  XPF: "fr-PF",
};

export const RESET_PASSWORD_SUCCESS_DEFAULTS = {
  reset_password_success_title: "Password Reset Successful",
  reset_password_success_description: "Your password has been reset successfully. You can now sign in with your new password.",
  reset_password_success_redirect_url: "/login",
  reset_password_success_redirect_label: "Sign In Now",
  reset_password_success_auto_redirect: "true",
} as const;

export const APP_SETTINGS = [
  // options settings
  {
    key: "currency_options",
    value: JSON.stringify(CURRENCY_OPTIONS),
    type: "json",
    category: "appearance",
    label: "Currency Options",
    description: "Available currency options",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "language_options",
    value: JSON.stringify(LANGUAGE_OPTIONS),
    type: "json",
    category: "appearance",
    label: "Language Options",
    description: "Available language options",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "theme_options",
    value: JSON.stringify(THEME_OPTIONS),
    type: "json",
    category: "appearance",
    label: "Theme Options",
    description: "Available theme options",
    sortOrder: 0,
    isPublic: true,
  },

  // currencies settings
  {
    key: "currency_locale_map",
    value: JSON.stringify(CURRENCY_LOCALE_MAP),
    type: "json",
    category: "currencies",
    label: "Currency Locale Map",
    description: "Mapping of currency to locale",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "zero_decimal_currencies",
    value: JSON.stringify(ZERO_DECIMAL_CURRENCIES),
    type: "json",
    category: "currencies",
    label: "Zero Decimal Currencies",
    description: "Currencies without decimal fractions",
    sortOrder: 0,
    isPublic: true,
  },

  // feature settings
  { key: "allow_registration", value: "true", type: "boolean", category: "features", label: "Allow Registration", description: "Allow new users to register", sortOrder: 0, isPublic: false },
  { key: "maintenance_mode", value: "false", type: "boolean", category: "features", label: "Maintenance Mode", description: "Put app in maintenance mode", sortOrder: 0, isPublic: false },

  // limits settings
  {
    key: "max_accounts_per_user",
    value: "10",
    type: "number",
    category: "limits",
    label: "Max Accounts Per User",
    description: "Maximum accounts a user can create",
    sortOrder: 0,
    isPublic: false,
  },
  {
    key: "max_categories_per_user",
    value: "50",
    type: "number",
    category: "limits",
    label: "Max Categories Per User",
    description: "Maximum custom categories per user",
    sortOrder: 0,
    isPublic: false,
  },
  {
    key: "max_password_age_days",
    value: "90",
    type: "number",
    category: "limits",
    label: "Password Expiry Days",
    description: "Number of days before a user's password expires and must be changed",
    sortOrder: 0,
    isPublic: false,
  },

  // app information settings
  { key: "app_version", value: "2.0.0", type: "string", category: "app_information", label: "App Version", description: "Current application version", sortOrder: 1, isPublic: true },
  { key: "app_created", value: "January 1, 2026", type: "string", category: "app_information", label: "Created", description: "Application creation date", sortOrder: 2, isPublic: true },
  { key: "app_build_number", value: "2026.06.06", type: "string", category: "app_information", label: "Build Number", description: "Current application build number", sortOrder: 3, isPublic: true },
  { key: "app_environment", value: "Production", type: "string", category: "app_information", label: "Environment", description: "Current application environment", sortOrder: 4, isPublic: true },

  // general information settings
  {
    key: "footer_copyright",
    value: "© 2026 Finarthax. All rights reserved.",
    type: "string",
    category: "general_information",
    label: "Footer Copyright",
    description: "Copyright text displayed in the website footer",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "social_login_separator",
    value: "Or continue with",
    type: "string",
    category: "general_information",
    label: "Social Login Separator Text",
    description: "Text displayed between the login form and social authentication buttons",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "signin_text",
    value: "Sign in",
    type: "string",
    category: "general_information",
    label: "Register Link Text",
    description: "Text for the sign up link",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "signup_text",
    value: "Sign up",
    type: "string",
    category: "general_information",
    label: "Login Link Text",
    description: "Text for the sign in link",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "google_signup_button",
    value: "Sign up with Google",
    type: "string",
    category: "general_information",
    label: "Google Sign Up Button Text",
    description: "Text displayed on the Google sign up button",
    sortOrder: 0,
    isPublic: true,
  },

  // Home page information settings
  {
    key: "home_title",
    value: "Finarthax",
    type: "string",
    category: "home_page_information",
    label: "Home Title",
    description: "Main title on homepage",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "home_description",
    value: "Record your transactions instantly, no login required",
    type: "string",
    category: "home_page_information",
    label: "Home Description",
    description: "Homepage description",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "how_it_works_title",
    value: "How it works:",
    type: "string",
    category: "home_page_information",
    label: "How It Works Title",
    description: "How it works section title",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "ready_for_more_title",
    value: "Ready for More?",
    type: "string",
    category: "home_page_information",
    label: "Ready For More Title",
    description: "Marketing section title",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "ready_for_more_description",
    value: "Create a free account to sync your data, set budgets, and access powerful analytics",
    type: "string",
    category: "home_page_information",
    label: "Ready For More Description",
    description: "Marketing section description",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "how_it_works_content",
    value: JSON.stringify([
      "Record transactions without creating an account",
      "Transactions saved locally on your device",
      "Perfect for quick expense tracking on the go",
      "Sign up later to sync and access advanced features",
    ]),
    type: "json",
    category: "home_page_information",
    label: "How It Works Content",
    description: "How it works section bullet points",
    sortOrder: 0,
    isPublic: true,
  },

  // Login page information settings
  {
    key: "login_title",
    value: "Welcome back",
    type: "string",
    category: "login_page_information",
    label: "Login Title",
    description: "Login title on login page",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "login_description",
    value: "Sign in to continue to your account",
    type: "string",
    category: "login_page_information",
    label: "Login Description",
    description: "Login page description",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "login_forgot_password_text",
    value: "Forgot password?",
    type: "string",
    category: "login_page_information",
    label: "Forgot Password Text",
    description: "Text displayed for the forgot password link",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "login_prompt_text",
    value: "Already have an account?",
    type: "string",
    category: "login_page_information",
    label: "Login Prompt Text",
    description: "Text displayed before the sign in link",
    sortOrder: 0,
    isPublic: true,
  },

  // Register page information settings
  {
    key: "register_title",
    value: "Create account",
    type: "string",
    category: "register_page_information",
    label: "Register Title",
    description: "Register title on register page",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "register_description",
    value: "Get started with your free account",
    type: "string",
    category: "register_page_information",
    label: "Register Description",
    description: "Register page description",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "register_password_requirements",
    value: "Password must contain:",
    type: "string",
    category: "register_page_information",
    label: "Password Requirements Title",
    description: "Title displayed above the password requirements list",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "register_password_requirements_list",
    value: JSON.stringify(["At least 8 characters", "One uppercase letter", "One lowercase letter", "One number"]),
    type: "json",
    category: "register_page_information",
    label: "Password Requirements",
    description: "List of password requirements displayed on authentication forms",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "register_button_create_account_text",
    value: "Create Account",
    type: "string",
    category: "register_page_information",
    label: "Create Account Button Text",
    description: "Text displayed on the create account button",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "register_confirmation_text",
    value: "I confirm that the information provided is accurate.",
    type: "string",
    category: "register_page_information",
    label: "Registration Confirmation Text",
    description: "Confirmation statement displayed during user registration",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "register_prompt_text",
    value: "Don't have an account?",
    type: "string",
    category: "register_page_information",
    label: "Register Prompt Text",
    description: "Text displayed before the sign up link",
    sortOrder: 0,
    isPublic: true,
  },

  // Forgot password page information settings
  {
    key: "forgot_password_title",
    value: "Forgot your password?",
    type: "string",
    category: "forgot_password_page_information",
    label: "Forgot Password Title",
    description: "Main heading displayed on the forgot password page",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "forgot_password_description",
    value: "No worries! Enter your email address and we'll send you a link to reset your password.",
    type: "string",
    category: "forgot_password_page_information",
    label: "Forgot Password Description",
    description: "Description displayed below the forgot password title",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "forgot_password_notice",
    value: "We'll send you an email with instructions to reset your password. The link will be valid for 1 hour.",
    type: "string",
    category: "forgot_password_page_information",
    label: "Forgot Password Notice",
    description: "Information displayed before the reset password button",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "forgot_password_button_text",
    value: "Send Reset Link",
    type: "string",
    category: "forgot_password_page_information",
    label: "Send Reset Link Button Text",
    description: "Text displayed on the send reset link button",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "forgot_password_prompt_text",
    value: "Back to Sign In",
    type: "string",
    category: "forgot_password_page_information",
    label: "Back to Sign In Text",
    description: "Text displayed for the back to sign in link",
    sortOrder: 0,
    isPublic: true,
  },

  // Reset password page information settings
  {
    key: "reset_password_title",
    value: "Reset your password",
    type: "string",
    category: "reset_password_page_information",
    label: "Reset Password Title",
    description: "Main heading displayed on the reset password page",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "reset_password_description",
    value: "Enter your new password below",
    type: "string",
    category: "reset_password_page_information",
    label: "Reset Password Description",
    description: "Description displayed below the reset password title",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "reset_password_requirements",
    value: "Password requirements:",
    type: "string",
    category: "reset_password_page_information",
    label: "Password Requirements Title",
    description: "Title displayed before the password requirements list",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "reset_password_requirements_list",
    value: JSON.stringify(["At least 8 characters long", "Must match confirmation"]),
    type: "json",
    category: "reset_password_page_information",
    label: "Password Requirements",
    description: "List of password requirements displayed on authentication pages",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "reset_password_button_text",
    value: "Reset Password",
    type: "string",
    category: "reset_password_page_information",
    label: "Reset Password Button Text",
    description: "Text displayed on the reset password button",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "reset_password_prompt_text",
    value: "Remember your password?",
    type: "string",
    category: "reset_password_page_information",
    label: "Remember Password Text",
    description: "Text displayed before the sign in link",
    sortOrder: 0,
    isPublic: true,
  },

  // Reset password success page information settings
  {
    key: "reset_password_success_title",
    value: "Password Reset Successful",
    type: "string",
    category: "reset_password_success_page_information",
    label: "Success Page Title",
    description: "Main heading displayed on the password reset success page",
    sortOrder: 0,
    isPublic: false,
  },
  {
    key: "reset_password_success_description",
    value: "Your password has been reset successfully. You can now sign in with your new password.",
    type: "string",
    category: "reset_password_success_page_information",
    label: "Success Page Description",
    description: "Description displayed on the password reset success page",
    sortOrder: 0,
    isPublic: false,
  },
  {
    key: "reset_password_success_redirect_url",
    value: "/login",
    type: "string",
    category: "reset_password_success_page_information",
    label: "Redirect URL",
    description: "Destination URL used when redirecting from the success page",
    sortOrder: 0,
    isPublic: false,
  },
  {
    key: "reset_password_success_redirect_label",
    value: "Sign In Now",
    type: "string",
    category: "reset_password_success_page_information",
    label: "Redirect Button Label",
    description: "Text displayed on the button that redirects the user to the configured URL",
    sortOrder: 0,
    isPublic: false,
  },
  {
    key: "reset_password_success_auto_redirect",
    value: "true",
    type: "boolean",
    category: "reset_password_success_page_information",
    label: "Enable Auto Redirect",
    description: "Whether users are automatically redirected after the countdown finishes",
    sortOrder: 0,
    isPublic: false,
  },
  {
    key: "reset_password_success_redirect_countdown_text",
    value: "Redirecting in {seconds} seconds...",
    type: "string",
    category: "reset_password_success_page_information",
    label: "Redirect Countdown Message",
    description: "Message displayed while counting down before automatic redirection",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "reset_password_success_redirect_countdown_seconds",
    value: "5",
    type: "string",
    category: "reset_password_success_page_information",
    label: "Redirect Countdown Duration",
    description: "Number of seconds to wait before automatically redirecting the user",
    sortOrder: 0,
    isPublic: true,
  },
  {
    key: "reset_password_success_button_text",
    value: "Go to Home",
    type: "string",
    category: "reset_password_success_page_information",
    label: "Secondary Button Label",
    description: "Text displayed on the secondary action button",
    sortOrder: 0,
    isPublic: true,
  },
] as const;
