export const USER_SETTINGS = [
  // notifications
  {
    key: "emailNotifications",
    value: "true",
    type: "boolean",
    category: "notifications",
    description: "Master switch for every email Finarthax sends you",
    icon: "📩",
  },
  {
    key: "weeklyReports",
    value: "true",
    type: "boolean",
    category: "notifications",
    description: "Receive a weekly financial summary by email",
    icon: "📊",
  },
  {
    key: "transactionAlerts",
    value: "true",
    type: "boolean",
    category: "notifications",
    description: "Confirm on screen whenever a transaction is recorded",
    icon: "🔔",
  },
  {
    key: "budgetAlerts",
    value: "true",
    type: "boolean",
    category: "notifications",
    description: "Warn me when a budget approaches its limit",
    icon: "💰",
  },
  {
    key: "budgetAlertThreshold",
    value: "80",
    type: "number",
    category: "notifications",
    description: "How much of a budget must be used before it is flagged",
    icon: "🎯",
  },
  {
    key: "recurringReminders",
    value: "true",
    type: "boolean",
    category: "notifications",
    description: "Surface recurring transactions that are due",
    icon: "🔁",
  },

  // appearance
  {
    key: "language",
    value: "en",
    type: "string",
    category: "appearance",
    description: "Interface language",
    icon: "🌐",
  },
  {
    key: "currency",
    value: "IDR",
    type: "string",
    category: "appearance",
    description: "Currency every amount is displayed in",
    icon: "💰",
  },
  {
    key: "theme",
    value: "system",
    type: "string",
    category: "appearance",
    description: "Interface theme",
    icon: "🎨",
  },
  {
    key: "dateFormat",
    value: "dd MMM yyyy",
    type: "string",
    category: "appearance",
    description: "How dates are written across the app",
    icon: "📅",
  },

  // privacy
  {
    key: "hideAmounts",
    value: "false",
    type: "boolean",
    category: "privacy",
    description: "Mask every amount until you turn this off",
    icon: "🙈",
  },
  {
    key: "publicQuickBalances",
    value: "false",
    type: "boolean",
    category: "privacy",
    description: "Show your account balances on the public quick-entry page after entering your email",
    icon: "👁️",
  },

  // general
  {
    key: "itemsPerPage",
    value: "20",
    type: "number",
    category: "general",
    description: "Rows shown per page in lists",
    icon: "📄",
  },
  {
    key: "defaultTransactionType",
    value: "EXPENSE",
    type: "string",
    category: "general",
    description: "Type preselected when adding a transaction",
    icon: "⚡",
  },
  {
    key: "recurringLookaheadDays",
    value: "14",
    type: "number",
    category: "general",
    description: "How far ahead upcoming recurring transactions are shown",
    icon: "📆",
  },
];
